#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Jun 22 19:22:54 2021

@author: andreavergara
"""

print("Hola")
3+3
print("Andreya")
print(type("Andreya"))
print(type(5))
print(type(True))
print(type(7.5))

print(1==1)
print(1!=2)
print(2>2)
print(2<4)
print(4<=6)
print(8<=6)
print((1>1)and(3==3))
print((1>1)or(3==3))


x=5
print(type(x))
suma=x+2
print(suma)