#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Jun 24 20:54:54 2021

@author: andreavergara
"""

# Create a list of the BRICS countries
country = [ 
            "Brazil", 
            "Russia", 
            "India", 
            "China", 
            "South Africa"
          ]

"""Create a dictionary of BRICS capitals.
Note that South Africa has
 3 capitals. Therefore, we embed a list inside
the dictionary.
"""

capitals = {
    "Brazil": "Brasilia",
    "Russia": "Moscow",
    "India": "New Delhi",
    "China": "Beijing",
    "South Africa": [
                        "Pretoria",
                        "Cape Town",
                        "Bloemfontein"
                    ]
           }

# Print the list and dictionary
print( country) #habian comillas innecesarias 
print( capitals)
"""
What response did you get?
Why did the list and dictionary
 contents not print? Comillas extras 
Fix the code and run the script again.
"""

print( capitals["South Africa"][1])

"""
Why did you get an error for the
 2nd capital of South Africa?  #me hacia falta un corchete 
Hint: Check the syntax for the index value.
"""

