#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Jun 25 14:11:16 2021

@author: andreavergara
"""
"""
Para trabajar con los valores en los diccionarios usamos 
llaves. Para ver el valor o imprimir usar print
Diccionario no almacena valores repetidos. Es un conjunto de datos no ordenado se puden añadir. Es posible hacer consultar 
Diccionario funciona en llave 
Valores asociados a una llave seguido por el valor asociado

"""
dict1= {"R1": "10.10.0.1",
        "R2":"10.10.0.2",
        5:"1713141515", 
        "Juan": "099999",
        "ID1":52.5, 
        "ID2":8}
print(dict1,"\n"*2)
print(type(dict1))

print(dict1,"\n"*2)
print(dict1["R1"])

dict1["R1"]= "10.1.1.1" #agrego un valor 
"R2" in dict1
dict1["AP1"]="10.10.10.1"
dict1["AP2"]="10.10.10.1"
dict1["AP2"]="10.10.10.11"
"10.10.10.1" in dict1
del dict1[5] #elimino un valor en posicion 5

print(dict1) #imprimo diccionario con nuevos valores 